name: GuestUnlock
main: se.myller.guestunlock2.Main
version: 3.0
description: >
             This plugin is used to send a message to admins when a player types the correct password.
commands:
  guestunlock:
    description: Sends password to admins
    usage: /<command> [Password]
    aliases: [gunlock, gu]
    permission-message: You dont have sufficent permissions! You are missing <permission>
    permission: GuestUnlock.guest
  gupassword:
    description: Changes the correct password
    usage: /<command> [New Password]
    aliases: [gadmin, gpassword]
    permission-message: You dont have sufficent permissions! You are missing <permission>
    permission: GuestUnlock.admin

permissions:
  guestunlock.guest:
    description: Seen as a Guest
    default: false
  guestunlock.moderator:
    description: See message when someone sends the correct password
    default: false
  guestunlock.admin:
    description: Change the password
    default: op
    children:
      guestunlock.moderator: true